### PR TITLE
Add license (GPLv3) - towards #9

### LINKED ISSUE #9: make c-beam-droid available in F-droid
Offer the app on f-droid for those without an google-account.

### PR DESCRIPTION
**Pull request by ligi**
needed for getting it on f-droid to close #9

### CODE REVIEW

**Comment by ligi** [comment]
ping @cmile

**Comment by cmile** [comment]
sorry I left the comment in another issue: is it alternativlos to use GPLv3? I had licensed c-beam under WTFPL and would like to keep it that way if possible. I could not find any information about GPLv3 being mandatory.

**Comment by ligi** [comment]
No it is not alternativlos - there are some apps on f-droid licensed WTFPL - but it needs to have a license - currently there is none at all ..
Can you add the license?

**Comment by cmile** [comment]
done

**Pull request closed without merging**
